### ISSUE TITLE
Problems upgrading to MongoDB 3.2

### ISSUE THREAD

**Issue by vventur** [sous-chefs/mongodb#105]
I tried using the branch Mongodb-v3 to upgrade to MongoDB-3.2, however on running the script it is not able to find the nproc.erb file under different file directories.
Using https://github.com/edelight/chef-mongodb I am not able to upgarde to 3.2 either because it fails to create the replicaset since the config file formats are different for versions 2.6 and above. Do you guys have any solutions to upgrade to 3.2? Thank you.

**Comment by gsaslis** [comment]
very similar problems here
@vventur did you ever get round this? 
#102 doesn't look very promising

**Comment by robertomoutinho** [comment]
missing nproc.erb here also...

**Comment by gsaslis** [comment]
so, the way i managed to install 3.2 on ubuntu 14.04 was with the following changes: 

1. replaced 
`include_recipe 'mongodb::mongodb_org_repo'`
with 
```
apt_repository 'mongodb' do
  uri 'http://repo.mongodb.org/apt/ubuntu/'
  distribution "#{node['lsb']['codename']}/mongodb-org/3.2"
  components ['multiverse']
  keyserver 'keyserver.ubuntu.com'
  key 'EA312927'
  action :add
end
```

2. Overriden both package_name and package_version: 
```
node['mongodb']['package_name] = 'mongodb-org'
node['mongodb']['package_version'] = '3.2.11'
```

I know this is far from the generic solution needed for the cookbook, but it's a workaround that allows ppl to keep using this cookbook, while the 3.2 rewrite is pending, so just thought I'd share FWIW.

**Comment by shortdudey123** [comment]
@gsaslis awesome! thanks for including that info here

**Comment by damacus** [comment]
Adding this to the 1.0.0 rewrite, as 3.2 should be our default now.

**Comment by shortdudey123** [comment]
Completed with the v1 rewrite
