### ISSUE TITLE
mongod instance starts instead of mongodb

### ISSUE THREAD

**Issue by ngphban** [sous-chefs/mongodb#108]
Hi,
Thank your for this great cookbook

I could deploy successfully this cookbook with the latest code in its repo (master).
However, after completing the chef run on my vagrant box, I saw the mongod instance was started, in stead of mongodb.

```
root@server01:/home/vagrant# service mongod status
mongod start/running, process 5440
root@server01:/home/vagrant# service mongodb status
mongodb stop/waiting
```

The mongod instance allows anonymous access on its databases, which is the case I don't need

```
root@server01:/home/vagrant# mongo localhost
MongoDB shell version: 2.6.12
connecting to: localhost
Welcome to the MongoDB shell.
For interactive help, type "help".
For more comprehensive documentation, see
    http://docs.mongodb.org/
Questions? Try the support group
    http://groups.google.com/group/mongodb-user
> show databases
admin  0.078GB
local  0.078GB
> show users
> use admin
switched to db admin
> show users
{
    "_id" : "admin.admin",
    "user" : "admin",
    "db" : "admin",
    "roles" : [
        {
            "role" : "root",
            "db" : "admin"
        },
        {
            "role" : "userAdminAnyDatabase",
            "db" : "admin"
        },
        {
            "role" : "dbAdminAnyDatabase",
            "db" : "admin"
        }
    ]
}
> exit
```

My work-around is: stop mongod instance and start the mongodb. With this, I'm able to force authentication against access on my databases

```
root@server01:/home/vagrant# service mongod stop
mongod stop/waiting
root@server01:/home/vagrant# service mongodb start
mongodb start/running, process 5621
root@server01:/home/vagrant# mongo localhost 
MongoDB shell version: 2.6.12
connecting to: localhost
> show dbs
2016-04-08T01:52:03.387+0000 listDatabases failed:{
    "ok" : 0,
    "errmsg" : "not authorized on admin to execute command { listDatabases: 1.0 }",
    "code" : 13
} at src/mongo/shell/mongo.js:47
> 
```

My questions:
- Is this an intention of the cookbook to make admins manually switch between two instances (mongod & mongodb)?
- Any workarounds in the code so I don't have to manually switch over each instances? My case is I will deploy this cookbook automatically on production with mongdb instance started and mongod instance stopped. I don't want everybody can access my database server without any credentials.

Below are my role attributes

```
$ knife role show mongodb
chef_type:           role
default_attributes:
description:         
env_run_lists:
json_class:          Chef::Role
name:                mongodb
override_attributes:
  authentication:
    password: MYPASSWORD
    username: admin
  mongodb:
    admin:
      database: admin
      password: MYPASSWORD
      roles:
        root
        userAdminAnyDatabase
        dbAdminAnyDatabase
      username: admin
    config:
      auth: true
    install_method: mongodb-org
run_list:
  recipe[mongodb]
  recipe[mongodb::user_management]
```

I also attached logs of my chef-client run and Vagrant file for your info.
[Vagrant.zip](https://github.com/chef-brigade/mongodb-cookbook/files/209704/Vagrant.zip)
[Chef-client.zip](https://github.com/chef-brigade/mongodb-cookbook/files/209706/Chef-client.zip)

My vagrant box info:
- Ubuntu 14.04 LTS
- Vagrant 1.8.1

**Comment by prestonj** [comment]
I had this issue as well (mongod started instead of mongodb). My solution was to force the cookbook to use /etc/init/mongod.conf (thus overwriting the old configuration) instead of the default script location of /etc/init/mongodb.conf.

In my attributes file:
default['mongodb']['default_init_name'] = 'mongod'

I was using Ubuntu 14.04 LTS and Mongo 2.6.12 for a sharded/replicaset + configservers environment. I can't comment on any of the user access stuff mentioned.

**Comment by jkulak** [comment]
I had the same issue. Ubuntu 14.04 LTS.

In my recipe, I had:
```
include_recipe 'mongodb::mongodb_org_repo'
include_recipe 'mongodb::default'
include_recipe 'mongodb::user_management'
```

I don't remember why I was using `mongodb_org_repo` but after removing it, everything worked well, and Chef was starting the mongodb service.

**Comment by damacus** [comment]
Looks like we'll be doing some refactoring of the user_management & org_repo when we rewrite this.

**Comment by shortdudey123** [comment]
Closing since the process is called `mongod` instead of `mongodb` now per Mongo's packaging and the current rewrite
