### ISSUE TITLE
Remove Python Dependency

### ISSUE THREAD

**Issue by damacus** [sous-chefs/mongodb#119]
Deprecate Python in favour of [poise-python](https://supermarket.chef.io/cookbooks/poise-python)

    Deprecated features used!
      method access to node attributes (node.foo.bar) is deprecated and will be removed in Chef 13, please use bracket syntax (node["foo"]["bar"]) at 3 locations:
        - /opt/kitchen/cache/cookbooks/python/attributes/default.rb:23:in `from_file'
        - /opt/kitchen/cache/cookbooks/python/attributes/default.rb:24:in `from_file'
        - /opt/kitchen/cache/cookbooks/python/attributes/default.rb:39:in `from_file'

**Comment by shortdudey123** [comment]
Completed
