### ISSUE TITLE
Chef 11 compatibility - build-essential

### ISSUE THREAD

**Issue by antonio-osorio** [sous-chefs/mongodb#133]
The install recipe, requires the build_essential resouce, which was introduced in v5.0 of the build-essential cookbook https://github.com/chef-cookbooks/build-essential/blob/master/CHANGELOG.md#v500-2016-06-03

As of build-essential v4.0, that cookbook is no longer compatible with Chef version 11. https://github.com/chef-cookbooks/build-essential/blob/master/CHANGELOG.md#v400-2016-05-12

While the change seems to be Windows related, it might be worth investigating/documenting Chef 11 compatibility. 

And adding the version information in this cookbook's metadata 

```
Recipe: chef_handler::default
  * remote_directory[/var/chef/handlers] action create
  Recipe: <Dynamically Defined Resource>
    * cookbook_file[/var/chef/handlers/README] action create (up to date)
     (up to date)

  ================================================================================
  Recipe Compile Error in /var/chef/cache/cookbooks/xxxx-mongodb3/recipes/default.rb
  ================================================================================

  NoMethodError
  -------------
  No resource or method named `build_essential' for `Chef::Recipe "install"'

  Cookbook Trace:
  ---------------
    /var/chef/cache/cookbooks/sc-mongodb/recipes/install.rb:4:in `from_file'
    /var/chef/cache/cookbooks/sc-mongodb/recipes/replicaset.rb:23:in `from_file'
    /var/chef/cache/cookbooks/xxxx-mongodb3/recipes/default.rb:1:in `from_file'
```

**Comment by shortdudey123** [comment]
Chef 11 is pretty old and will no longer be officially supported within the next 6 weeks so i am not sure there is a need to call out that in documentation or in code.
