### ISSUE TITLE
Dependencies error

### ISSUE THREAD

**Issue by totti339** [sous-chefs/mongodb#137]
Hi,

since your last commit (setting minimum version for build-essential to 5.0.0) the cookbook are not still compatible with chef 11.
Indeed build-essential 5.0.0 use compat_resource >= 12.10 which require chef 12.

Thomas

**Comment by shortdudey123** [comment]
Correct, since https://github.com/sous-chefs/mongodb/pull/135 breaks chef 11 compat, it won't be released to supermarket until the pending rewrite is done which drops chef 11 support entirely
