### ISSUE TITLE
Unable to create replicasets on AWS OpsWorks 

### ISSUE THREAD

**Issue by scoady** [sous-chefs/mongodb#138]
Hi -

I've tried this on Ubuntu 14/16, Amazon Linux, and RHEL via OpsWorks.

I'm running into issues with the sc-mongodb::replicaset recipe -- the standalone node worked fine when I ran that.

JSON passed into the mongo layer:
`{ "mongodb": {
    "cluster_name" : "cluster_rs"
  }
}`

Output from the logs:

`[2017-04-07T17:49:19+00:00] INFO: HTTP Request Returned 400 Bad Request: invalid search query: 'mongodb_cluster_name:cluster_rs AND        mongodb_is_replicaset:true AND        mongodb_config_replSet: AND        chef_environment:_default'
`

Is the attribute `mongodb_config_replSet` supposed to be blank? Perhaps that's why the request is 400'ing?

I am new with Chef, so if I'm doing something wrong, I apologize for the raised issue. Thanks in advance.

**Comment by scoady** [comment]
Closing this - I did not see this in the readme:
 "replSet is not set automatically"

Thanks!

**Comment by shortdudey123** [comment]
What version of the cookbook are you using?
What do you have `node['mongodb']['package_version']`?

**Comment by shortdudey123** [comment]
sounds good, feel free to reopen if needed
