### ISSUE TITLE
rs_member_ips is referenced but not initialized

### ISSUE THREAD

**Issue by k-popov** [sous-chefs/mongodb#179]
Variable `rs_member_ips` is referenced before it's set anywhere. Fist use is: https://github.com/sous-chefs/mongodb/blob/0b168a740a15435b1a2567f66add79beba4c625f/libraries/mongodb.rb#L134

The regression was most probably caused by 6f3f2caa88e7ee350f4be60a06d618d817c1d44e

**Comment by josephholsten** [comment]
Shoot. Think you could whip together a test case for me to reproduce this error? Or tell me the rough steps so I can code it myself? Clearly our testing for this component isn’t good enough.

**Comment by heaven** [comment]
A test case:
```ruby
include_recipe 'sc-mongodb::replicaset'
```
Then run chef-client, first time it works, second time fails on this line `sc-mongodb/libraries/mongodb.rb:134`

**Comment by k-popov** [comment]
In my understanding the issue arises when cluster members list changes. The condition that fails tries to detect the situation when IPs were used initially but changed to hostnames afterwards.

The following patch should fix this issue but I don't like this solution (duplication, more method parameters):
```diff
diff --git a/libraries/mongodb.rb b/libraries/mongodb.rb
index b591911..648ee65 100644
--- a/libraries/mongodb.rb
+++ b/libraries/mongodb.rb
@@ -32,11 +32,11 @@ class Chef::ResourceDefinitionList::MongoDB
   # if node['fqnd'] is a vagrant host, ignore it
   # node['mongodb']['replica_priority'] is required
   #
-  def self.create_replicaset_member(node)
+  def self.create_replicaset_member(node, force_use_ip)
     return {} if node['fqdn'] =~ /\.vagrantup\.com$/
 
     port = node['mongodb']['config']['mongod']['net']['port']
-    host = node['mongodb']['use_ip_address'] ? node['ipaddress'] : node['fqdn']
+    host = node['mongodb']['use_ip_address'] || force_use_ip ? node['ipaddress'] : node['fqdn']
     address = "#{host}:#{port}"
 
     member = {}
@@ -71,7 +71,7 @@ class Chef::ResourceDefinitionList::MongoDB
     end
 
     mongo_host = 'localhost'
-    mongo_port = node['mongodb']['config']['net']['port']
+    mongo_port = node['mongodb']['config']['mongod']['net']['port']
 
     begin
       connection = nil
@@ -89,7 +89,10 @@ class Chef::ResourceDefinitionList::MongoDB
     members.sort! { |x, y| x.name <=> y.name }
 
     rs_members = members.each_with_index.map do |member, n|
-      create_replicaset_member(member).merge('_id' => n)
+      create_replicaset_member(member, false).merge('_id' => n)
+    end
+    rs_member_ips = members.each_with_index.map do |member, n|
+      create_replicaset_member(member, true).merge('_id' => n)
     end
 
     Chef::Log.info(
```

**Comment by swalberg** [comment]
@k-popov are you able to check out #188 to see if that fixes your problem? I ran into this, too.
