### ISSUE TITLE
Contributors Wanted! 

### ISSUE THREAD

**Issue by damacus** [sous-chefs/mongodb#196]
We need more contributors for this cookbook, if you would like to help maintain this cookbook please drop your name here!

**Comment by swalberg** [comment]
We use this cookbook, I'd like to help where I can.

**Comment by damacus** [comment]
Awesome! 

Would you like to add yourself to the maintainers?

https://github.com/sous-chefs/terraform-github-org/blob/master/mongodb.tf

**Comment by swalberg** [comment]
Done https://github.com/sous-chefs/terraform-github-org/pull/86 
Thank you!
