### ISSUE TITLE
update edelight's tickets to reflect what has been resolved here

### ISSUE THREAD

**Issue by josephholsten** [sous-chefs/mongodb#71]
I don't want people to get lost at https://github.com/edelight/chef-mongodb

So I've created PR https://github.com/edelight/chef-mongodb/pull/399

and I've closed my tickets. Could someone go through the rest of them and point folks over here, especially if we've resolved their issue?

**Comment by zarry** [comment]
@josephholsten Can we really not get in touch with anyone from edelight?  Would be nice to either close that repo or put up a disclaimer/redirect at the top of the README.  Will take a while for ours to overtake theirs in google search land.

**Comment by tobami** [comment]
I do no longer work for edelight, or maintain `chef-mongodb` but I agree `chef-brigade` would be a better home for it, as edelight didn't contribute much in the last years and it was mostly others who maintained it.

That said, the person you need to ask is @thekorn , who originally did most of the work and would be the one who could help you there, if he agrees.

**Comment by shortdudey123** [comment]
@josephholsten should we consider this done w/ [RFC088](https://github.com/chef/chef-rfc/blob/master/rfc088-mongodb-cookbook-transfer.md)?

**Comment by josephholsten** [comment]
@shoekstra your call. I can do a manual review though.

**Comment by josephholsten** [comment]
actually, I went through and verified all the recent tickets all have pointers to here.

🔤

**Comment by shortdudey123** [comment]
sounds good 👍
