### ISSUE TITLE
 add chef-attribute-validator support

### ISSUE THREAD

**Issue by josephholsten** [sous-chefs/mongodb#74]
From https://github.com/edelight/chef-mongodb/issues/165

https://github.com/clintoncwolfe/chef-attribute-validator (guts of validator)

https://github.com/clintoncwolfe/attribute-validator (thin cookbook)

**Comment by shortdudey123** [comment]
Closing for now since the 2 repo's mentioned are pretty outdated (last commit over 18 months ago).
If we want to do this we should update them or find something different.

Generally speaking, i have not seen anything validate chef attributes besides the types and that they are there or not
