### ISSUE TITLE
 actually use configserver values in mongos

### ISSUE THREAD

**Issue by josephholsten** [sous-chefs/mongodb#76]
From https://github.com/edelight/chef-mongodb/issues/196

so far as I can tell, the configserver nodes in mogodb_instance are entirely unused. This seems to be in error.

**Comment by shortdudey123** [comment]
Looks like this is already being used correctly in master
https://github.com/sous-chefs/mongodb/blob/26006ad76837fdbc05417448930261d463a3226f/definitions/mongodb.rb#L41-L45

Not seeing any issues w/ this as part of the rewrite so i am removing this from the `1.0.0` milestone and closing
