### ISSUE TITLE
Break Backward Compatibility

### ISSUE THREAD

**Issue by josephholsten** [sous-chefs/mongodb#78]
From https://github.com/edelight/chef-mongodb/issues/308

Note: this ticket may be out of date.

Someday soon we're going to have to break backwards compatibility, and we may as well rip the bandage off. This is a tracking ticket for all the backwards incompatible changes that should go into the next breaking release (1.0?).
- allow arbitrary shard names
- separate shard and replicaset names
- remove references to 10gen
- support compound sharding keys
- stop creating a `mongodb_instance` in `mongodb::default`
- update default paths to match mongodb defaults
- use yaml format config, incompatible with < 2.6 mongo

**Comment by shortdudey123** [comment]
Moved from `1.1.0` to `1.0.0` since i cover most of this already in the rewrite

**Comment by shortdudey123** [comment]
Completed in v1 rewrite
- remove references to 10gen
- update default paths to match mongodb defaults
- use yaml format config, incompatible with < 2.6 mongo

Todo
- stop creating a mongodb_instance in mongodb::default
- support compound sharding keys
- allow arbitrary shard names
- separate shard and replicaset names

**Comment by shortdudey123** [comment]
- https://github.com/sous-chefs/mongodb/issues/75 => stop creating a mongodb_instance in mongodb::default
- https://github.com/sous-chefs/mongodb/issues/142 => support compound sharding keys
- https://github.com/sous-chefs/mongodb/issues/141 => allow arbitrary shard names
- https://github.com/sous-chefs/mongodb/issues/143 => separate shard and replicaset names
