### ISSUE TITLE
Test mongodb::replicaset

### ISSUE THREAD

**Issue by josephholsten** [sous-chefs/mongodb#79]
From https://github.com/edelight/chef-mongodb/issues/122

Requires [chef-solo-search](https://github.com/edelight/chef-solo-search) to fake out the results of [definitions/mongodb.rb:163](https://github.com/edelight/chef-mongodb/blob/master/definitions/mongodb.rb#L163):

``` ruby
    rs_nodes = search(
      :node,
      "mongodb_cluster_name:#{replicaset['mongodb']['cluster_name']} AND \
       recipes:mongodb\\:\\:replicaset AND \
       mongodb_shard_name:#{replicaset['mongodb']['shard_name']} AND \
       chef_environment:#{replicaset.chef_environment}"
    )
```

**Comment by shortdudey123** [comment]
Added in kitchen testing for this via https://github.com/sous-chefs/mongodb/pull/155
