### ISSUE TITLE
When specifying a package version, the packages below metapackage do not respect version

### ISSUE THREAD

**Issue by zarry** [sous-chefs/mongodb#80]
Originally from https://github.com/edelight/chef-mongodb/issues/378

When specifying a specific package version to install, the metapackage installed is of the correct version but the packages below that are not correct.

```
node.default['mongodb']['package_version'] = '2.6.7'
```

```
[lzarou@mpqa1mdb03 / ]$ dpkg -l | grep mongo
ii  mongodb-org                              2.6.7                            amd64        MongoDB open source document-oriented database system (metapackage)
ii  mongodb-org-mongos                       2.6.8                            amd64        MongoDB sharded cluster query router
ii  mongodb-org-server                       2.6.8                            amd64        MongoDB database server
ii  mongodb-org-shell                        2.6.8                            amd64        MongoDB shell client
ii  mongodb-org-tools                        2.6.8                            amd64        MongoDB tools
```

The mongo documentation talks about specifying the version for each subpackage during install.

http://docs.mongodb.org/manual/tutorial/install-mongodb-on-ubuntu/?_ga=1.205420498.331254452.1423066281#install-a-specific-release-of-mongodb

Is this a direction we should move in?  I don't mind throwing together a PR to install each of those packages separately for debian/ubuntu but I am curious as to thoughts before going in that direction.

**Comment by shortdudey123** [comment]
This was a packaging issue that was already fixed
