### ISSUE TITLE
Cookbook versioning and chef supermarket 

### ISSUE THREAD

**Issue by crwenner** [sous-chefs/mongodb#88]
Why is this cookbook not being versioned with the changes/fixes that are being added? Also, is there a reason this cookbook is not in supermarket.chef.io?

**Comment by luishdez** [comment]
We were waiting to see if we could get permissions from the original repo in supermarket. But we had no luck. So these days we're going to release it in supermarket under brigade-mongodb

https://github.com/chef-brigade/meta/issues/3

**Comment by josephholsten** [comment]
I've created a fork of https://github.com/edelight/chef-mongodb to put together a PR that points all users to us: https://github.com/chef-brigade/edelight-chef-mongodb-transition

If this seems like a good idea, we can probably get that finally merged (into github master) and released (at supermarket) for the upstream mongodb.

**Comment by josephholsten** [comment]
I'm thinking of adding a standard release process doc to meta, it would be useful to know if you can release with this process: https://github.com/chef-brigade/nano-cookbook/blob/master/RELEASE.md

**Comment by triccardi-systran** [comment]
For the migration:
* does this mean that users of the old supermarket `mongodb` would automatically use the new `brigade-mongodb`? Or only if they use the new version `~> 0.99.0`? Why is it `0.99.0` ?
* it could also help to add `replaces 'mongodb'` or `replaces 'mongodb', '< 1.0'` to our `metadata.rb`.

**Comment by josephholsten** [comment]
- it doesn't automatically migrate, we'd need to have wrapper recipes &c for that
- I picked `0.99.0` arbitrarily
- I've never used `replaces`, but that sounds fine

**Comment by scopenco** [comment]
When this cookbook will be released to supermarket.chef.io?

**Comment by runningman84** [comment]
any news?

**Comment by josephholsten** [comment]
see https://github.com/chef-brigade/mongodb-cookbook/pull/106
